source "https://rubygems.org"

gem 'jbundler'
gem 'sinatra'
gem 'rack-flash3'
gem 'twilio-ruby'
gem 'data_mapper'
#gem 'dm-sqlite-adapter' # dev SQLite DB adapter
#gem 'dm-postgres-adapter' # prod PostgreSQL adapter
#gem 'thin' # prod thin server
